# Generated by Django 5.0.1 on 2024-02-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.TextField(db_column='name', max_length=50, null=True)),
                ('c_image', models.ImageField(db_column='image', null=True, upload_to='category')),
                ('c_description', models.TextField(db_column='description', max_length=200, null=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, null=True)),
                ('email', models.TextField(max_length=100, null=True)),
                ('mob', models.PositiveIntegerField(null=True)),
                ('password', models.TextField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.TextField(db_column='name', max_length=50, null=True)),
                ('p_image', models.ImageField(db_column='image', null=True, upload_to='produts')),
                ('p_price', models.PositiveIntegerField(db_column='price', null=True)),
                ('p_description', models.TextField(db_column='description', max_length=200, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seller.category')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
